[package]
name = "fractal"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
indicatif = { version = "0.18", features = ["rayon"] }
rayon = "1.11.0"

